# Generated by Django 4.2.3 on 2023-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
                ('car', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeLoaction', models.CharField(max_length=100)),
                ('workLocation', models.CharField(max_length=100)),
                ('workTime', models.CharField(max_length=100)),
                ('workDays', models.CharField(max_length=100)),
            ],
        ),
    ]
